language: java
before_install:
  - sudo apt-get update
before_script:
  - java -version
notifications:
  email: false
env:
  global:
    - OPENAS2_FILE_SYSTEM_RUN=False
matrix:
  include:
    - os: linux
      dist: xenial
      language: java
      before_install:
        - sudo apt-get update
        - sudo apt list | grep jdk
        - sudo apt-get -y install openjdk-8-jdk-headless
        - sudo update-alternatives --display java
      script: ./mvnw.cmd test
    - os: windows
      language: shell
      before_install:
        - choco install openjdk
        - choco install maven
      script: ./mvnw test
