name: Java CI
on: [pull_request]
jobs:
  build:
    runs-on: [windows-latest, ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        java_version: [9, 16]
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK $
        uses: actions/setup-java@v2
        with:
          java-version: $
      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw test --file pom.xml
