name: Java CI
on: [pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [12, 13, 14, 15, 16]
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw test --file pom.xml --log-file maven.log
      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: execution-logs-${{ matrix.java_version }}-${{ matrix.os }}
          path: maven.log
          retention-days: 1
