name: Build and Push OpenAS2 Docker Images with Dynamic Versioning

on:
  workflow_dispatch:

env:
  IMAGE_NAME: openas2app
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    name: Build and Push Multi-Platform Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Latest Version from Docker Hub
        id: get_version
        run: |
          EXISTING_TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}/tags \
            | jq -r '.results[] | select(.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$")) | .name' \
            | sort -V | tail -1)

          if [ -z "$EXISTING_TAG" ]; then
            echo "No existing version found. Setting version to 1.0.0"
            NEW_VERSION="1.0.0"
          else
            echo "Found existing version: $EXISTING_TAG"
            IFS='.' read -r MAJOR MINOR PATCH <<< "$EXISTING_TAG"
            PATCH=$((PATCH+1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi

          echo "New version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push OpenAS2 Server Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Build and Push OpenAS2 Web UI Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_WebUI
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-web:${{ env.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-web:latest